on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Upload coverage report
        uses: codecov/codecov-action@v2

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
